services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    profiles: ["admin", "all"]
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    profiles: ["media", "all"]
    ports:
      - "8096:8096"
    volumes:
      - /home/yakshith/jellyfin/config:/config
      - /home/yakshith/jellyfin/cache:/cache
      - /mnt/e/courses/masterclass:/media:ro

volumes:
  portainer_data:
    external: true
